### ISSUE TITLE
No keystore, suggest re-create it with the "Secret Seed Mnemonic"

### ISSUE THREAD

**Issue by githare** [DigixGlobal/wallet-migration#1]
This tool says "No keystores found in LocalStorage - please upload one", but I don't have any, though I've created a wallet on app.digix.io and have the secret seed mnemonic.
Could you please add a link that would permit to re-create the keystore from the secret seed mnemonic?

**Comment by githare** [comment]
Thanks for the fix. Any ETA to apply it to the site?

**Comment by IstoraMandiri** [comment]
CC @tymat

**Comment by githare** [comment]
Thank you for the "restore mnemonic" stuff, but it only allows me to download the keystore, and moreover, it doesn't work :-( It asks me to choose a password, and when I click "download keystore", it freezes firefox for a few minutes, then when it "unfreezes", nothing happens.
If I reload the page, it still displays "No keystores found in LocalStorage - please upload one".

**Comment by IstoraMandiri** [comment]
@arno-github 

Hmm, the freezing is expected, but it should downloaded a keystore file once it unfreezes. I am able to re-create this in the latest Firefox (although it was working in older versions). 

I'll fix this issue in FF asap. Thanks for the report.

In the meantime, you can use Chrome, which should be working as intended.

**Comment by githare** [comment]
The "save as" box opens fine now (Firefox doesn't freeze...), but the file downloaded isn't encrypted with the password chosen (in fact it isn't encrypted at all) : it's a plain text file which isn't accepted by the page when trying to upload (Firefox says "couldn't read files").

**Comment by IstoraMandiri** [comment]
@arno-github The file generated is in the 'v3' format, compatible with geth and MyEtherWallet.

The file itself isn't encrypted, but has contents as such which is encrypted:

```
{
  "version": 3,
  "id": "xxx",
  "address": "xxx",
  "crypto": {
    "ciphertext": "xxx",
    "cipherparams": {
      "iv": "xxx"
    },
    "cipher": "aes-128-ctr",
    "kdf": "scrypt",
    "kdfparams": {
      "dklen": 32,
      "salt": "xxx",
      "n": 1024,
      "r": 8,
      "p": 1
    },
    "mac": "xxxx"
  }
}
```

It's not supposed to be compatible with the migration tool itself after it's been converted; please try uploading it into MyEtherWallet to test it out.

**Comment by githare** [comment]
Sorry I misunderstood the aim of this migration tool...
So how can I do to recover my keystore on LocalStorage from my mnemonic please? (that was my very question, see first post in this issue)
I explain : I transfered some ETH to my digix wallet a few weeks ago in order to buy DGX tokens, but when I came back to the app.digix.io, it said "No keystores found in LocalStorage - please upload one", so that I cannot recover my ETH on digix.io to buy DGX.

**Comment by IstoraMandiri** [comment]
@arno-github 

From the migration tool header:

_This tool converts the old style (Jan 2016) lightwallet keystore used by the Digix beta app into a more modern Geth and MyEtherWallet compatible version._

They keystore will have the same address as the one you created in the beta app, but using a more modern/compatible format, so it can be used by geth and MEW. Basically, you'll probably be wanting to use the keystore generated by the migration tool in another app, like Geth or MyEtherWallet, in order to recover your assets. Once you've converted and downloaded your new keystore, upload it into MEW, then transfer your ETH into another account.

**Comment by githare** [comment]
I recovered my assets, thanks, but what kind of keystore should I have, to upload on app.digix.io, in order to buy DGX???
Each time I click on "purchase DGX tokens / visit marketplace", it opens this "app.digix.io migration tool page", and as it cannot find any valid keystore, I cannot do anything except download mine from my mnemonic.
Am I so stupid I cannot understand how to buy DGX???

**Comment by weisnc** [comment]
I have the same problem，I cannot understand how to buy DGX?
The site https://app.digix.io/ says let me upload one keystores，
What's this “keystores”? Where do I get it?

**Comment by AdamWarren3** [comment]
I have the same issue. I never had a wallet like this to begin with. Seems only certain people are getting access to the DGX Token..

**Comment by tymat** [comment]
DGX 2.0 has not launched yet.  The wallet migration tool is for our beta users who participated after our launch of DGX 1.0 platform.
